name: wemolo_parking
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  appinio_swiper: ^2.1.1
  bloc_test: ^9.1.7
  dartz: ^0.10.1
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.3
  get_it: ^7.7.0
  injectable: ^2.4.2
  json_annotation: ^4.9.0
  logger: ^2.3.0
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1
  test: ^1.24.9

flutter:
  uses-material-design: true
